config/routes.rb
Rails.application.routes.draw do
  
  resources :aplications
  # resources :reviews
  # project/id/new
 
  resources :projects do 
    resources :reviews, except: [:show, :index]
    resources :employers

    member do
      get 'apply'
    end

     
     
    
  end
  get '/confirm/:id', to: "projects#confirm_complete"
  root 'welcome#index'

  resources :messages, only: [:index, :create] do
    get '/chat/:user_id', action: :chat, as: 'chat', on: :collection
  end

  devise_for :employers, :controllers => { :registrations => 'employers/registrations' }
  devise_for :developers, path: 'developers', :controllers => { registrations: 'developers/registrations' }
 
  get '/developers', to: 'developers#index'
  get '/developers/:id', to: 'developers#show', as: 'developer'
  

  as :employers do
    get '/employers', to: 'employers#index'
    get '/employers/:id', to: 'employers#show', as: 'employer'
    get '/employers/my/projects', to: 'employers#index_projects'
  end

  as :developers do
    get '/developers/my/projects', to: 'developers#index_projects'
  end
  
  get '/dashboard', to: 'welcome#dashboard'
  get '/login', to: 'welcome#login'
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :employer
    belongs_to :developer, optional: true
    has_many :reviews
    has_many :aplications

    filterrific(
        available_filters: [
          :project_status,
          :plattform_mobile,
          :plattform_desktop,
          :platform_tablet,
          :assets_text,
          :assets_images,
          :assets_videos,
          :assets_audio,
          :assets_database,
          :due_date_less_then_month,
          :due_date_one_month,
          :due_date_three_month, 
          :due_date_plus_three_month,
          :pages_landing_pages,
          :pages_two_pages,
        ]
      )

    scope :plattform_mobile, ->(query) { where(plattform_mobile: query) }
    scope :plattform_desktop, ->(query) { where(plattform_desktop: query) }
    scope :project_status, ->(query) { where(project_status: query) }
    scope :platform_tablet, ->(query) { where(platform_tablet: query) }
    scope :assets_text, ->(query) { where(assets_text: query) }
    scope :assets_images, ->(query) { where(assets_images: query) }
    scope :assets_videos, ->(query) { where(assets_videos: query) }
    scope :assets_audio, ->(query) { where(assets_audio: query) }
    scope :assets_database, ->(query) { where(assets_database: query) }
    scope :due_date_less_then_month, ->(query) { where(due_date_less_then_month: query) }
    scope :due_date_one_month, ->(query) { where(due_date_one_month: query) }
    scope :due_date_three_month, ->(query) { where(due_date_three_month: query) }
    scope :due_date_plus_three_month, ->(query) { where(due_date_plus_three_month: query) }
    scope :pages_landing_pages, ->(query) { where(pages_landing_pages: query) }
    scope :pages_two_pages, ->(query) { where(pages_two_pages: query) }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :apply, :confirm_complete]

  # GET /projects
  # GET /projects.json
  def index
   
    binary_select_options = [['Yes', true], ['No', false]]
    status_of_project = [['Open', 'open'], ['In Process', 'in process'], ['Complete', 'complete']]

    @filterrific = initialize_filterrific(
      Project,
      params[:filterrific],
      select_options: {
        project_status: status_of_project,
        plattform_mobile: binary_select_options,
        plattform_desktop: binary_select_options,
        platform_tablet: binary_select_options,
        assets_text: binary_select_options,
        assets_images: binary_select_options,
        assets_videos: binary_select_options,
        assets_audio: binary_select_options,
        assets_database: binary_select_options,
        due_date_less_then_month: binary_select_options,
        due_date_one_month: binary_select_options,
        due_date_three_month: binary_select_options,
        due_date_plus_three_month: binary_select_options,
        pages_landing_pages: binary_select_options,
        pages_two_pages: binary_select_options,

      },
      default_filter_params: {},
      sanitize_params: false,
    ) or return
    @projects = @filterrific.find.order(created_at: :desc)
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @reviews = Review.where(project_id: @project.id).order("created_at DESC")
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
 

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        # Update project status to open
        if @project.developer and @project.project_status == 'open'
          @project.update(project_status: 'in process')
        end
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm_complete
     puts "hello"
    @project = Project.find(params[:id])
    @project.update(project_status: "complete")
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def apply
    respond_to :js
    unless current_developer
      return head 403
    end

    attributes = {
      developer: current_developer,
      project: @project
    }

    if Aplication.exists?(attributes) 
      return head 422
    end

    Aplication.create!(attributes)
  end

  def assign_developer
    respond_to :js
    unless current_employer
      return head 403
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end
      
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:developer_id, :employer_id, :project_status, :project_name, :project_description, :project_review, :plattform_mobile, :plattform_desktop, :platform_tablet, :assets_text, :assets_images, :assets_videos, :assets_audio, :assets_database, :due_date_less_then_month, :due_date_one_month, :due_date_three_month, :due_date_plus_three_month, :pages_landing_pages, :pages_two_pages)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
    <% if project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
        <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
<div class="project-container">

  <div class="project-main">

<div class="project-container">
  <div class="project-main">
  <div class="field">
   <%= form.hidden_field :developer_id %>
   <%= form.hidden_field :developer_id %>
   <%= form.hidden_field  :employer_id %>
    <%= form.hidden_field  :employer_id, :value => current_employer.id %>
    <%= form.label :project_name %>
    <%= form.text_field :project_name %>
    <%= form.label :project_description %>
    <%= form.text_field :project_description %>
  </div>
   <div class="actions">
    <%= form.submit %>
  </div>
  <% if @project.project_status == "open" %>
    <%= link_to '<i class="fas fa-trash-alt"></i> Delete Project'.html_safe, project_path(@project), method: :delete, data: { confirm: 'Are you sure you want to delete the project?' },  id: 'delete_project' %>
  <% end %>

  </div>

  <div class="project-side">
    <div class="field">
      <strong><%= form.label :project_status %></strong>
      <%= form.text_field :project_status, :value => 'open'%><br>
      <br>
      <strong>Due Date</strong><br>
      <%= form.check_box :due_date_less_then_month %> Less than 1 month<br>
      <%= form.check_box :due_date_one_month %> 1 month<br>
      <%= form.check_box :due_date_three_month %> 3 months<br>
      <%= form.check_box :due_date_plus_three_month %> 3+ months<br>
    <br>
    <strong>Platform</strong><br>
      <%= form.check_box :plattform_desktop %> Desktop <br>
      <%= form.check_box :plattform_mobile %> Mobile <br>
      <%= form.check_box :platform_tablet %> Tablet <br>
    <br>
    <strong>Assets</strong><br>
      <%= form.check_box :assets_text %> Text <br>
      <%= form.check_box :assets_images %> Images <br>
      <%= form.check_box :assets_videos %> Videos <br>
      <%= form.check_box :assets_audio %> Audio <br>
      <%= form.check_box :assets_database %> Database<br>
    <br>
    <strong>Page(s)</strong> <br>
      <%= form.check_box :pages_landing_pages %> Landing pages <br>
      <%= form.check_box :pages_two_pages %> 2+ pages<br>
    <br>
  </div>
  <% end %>
</div>

app/views/projects/_form_developer_apply.html.erb
<div id="project-dev-actions">
    <%= link_to 'Apply', apply_project_path(@project), remote: true, id: "project-apply-button" %> 
</div>   

app/views/projects/_form_employer_select_applicant.html.erb
<% if @project.aplications.length > 0 %>
    <div id="applications-form">
        <% if @project.developer_id %>

        <% else %>
            <h3>Applicants:</h3>

            <%= form_with(model: @project) do |form| %>
               <p><%= form.collection_radio_buttons :developer_id, @project.aplications, :developer_id, :developer_name %></p>
                <%= form.submit 'Confirm' %>
            <% end %>
        <% end %>
    </div>
<% end %>

app/views/projects/_list.html.erb
<div id="projects_list">
    <table class="ui selectable celled table" >
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Status</th>
        </tr>
    </thead>
    <% @projects.each do |project| %>
    <tbody>
        <tr>
        <td><strong><%= link_to project.project_name, project_path(project), class: "title" %></strong></td>
        <td><%= project.project_description%></td>
        <td><%= project.project_status%></td>
        </tr>
    </tbody>
     <% end %>
    </table>
</div>

app/views/projects/apply.js.erb
$("#project-apply-button").fadeOut(300, () => {
    $('#project-dev-actions').text('Application accepted');
})

app/views/projects/confirm_complete.js.erb
    $('#confirm_complete').replaceWith('The project is complete! Congratulations!');
    $('#please_confirm').fadeOut(300);
    $( "#project-status" ).replaceWith("complete");

app/views/projects/edit.html.erb
<div class="top-buttons">
    <h3><%= link_to '<i class="fas fa-arrow-left"></i>'.html_safe + ' Back to ' + "#{@project.project_name}", project_path(@project) %></h3>
</div>
<h3>Edit Project</h3>
<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="projects"> 
  <%= form_for_filterrific @filterrific do |f| %>
    <span class="small"><strong>Search Filter</strong></span>
    <div class="project-filter">
      <div class="filter-col">
        <strong><label>Status</label></strong>
        <%= f.select(
          :project_status,
          @filterrific.select_options[:project_status],
          include_blank: '- Any -' 
        ) %>
      </div>

      <div class="filter-col">
        <strong>Platform</strong>

        <label>Desktop</label>
        <%= f.select(
          :plattform_desktop,
          @filterrific.select_options[:plattform_desktop],
          include_blank: '- Any -' 
        ) %>

        <label>Mobile</label>
        <%= f.select(
          :plattform_mobile,
          @filterrific.select_options[:plattform_mobile],
          include_blank: '- Any -' 
        ) %>

        <label>Tablet</label>
        <%= f.select(
          :platform_tablet,
          @filterrific.select_options[:platform_tablet],
          include_blank: '- Any -' 
        ) %>
      </div>

      <div class="filter-col">
      <strong>Assets</strong>
        <label>Text</label>
        <%= f.select(
          :assets_text,
          @filterrific.select_options[:assets_text],
          include_blank: '- Any -' 
        ) %>
      
        <label>Images</label>
        <%= f.select(
          :assets_images,
          @filterrific.select_options[:assets_images],
          include_blank: '- Any -' 
        ) %>
    
        <label>Videos</label>
        <%= f.select(
          :assets_videos,
          @filterrific.select_options[:assets_videos],
          include_blank: '- Any -' 
        ) %>

        <label>Audio</label>
        <%= f.select(
          :assets_audio,
          @filterrific.select_options[:assets_audio],
          include_blank: '- Any -' 
        ) %>
      
        <label>Database</label>
        <%= f.select(
          :assets_database,
          @filterrific.select_options[:assets_database],
          include_blank: '- Any -' 
        ) %>
      </div>

      <div class="filter-col">
      <strong>Due Date</strong>
        <label> < 1 month</label>
        <%= f.select(
          :due_date_less_then_month,
          @filterrific.select_options[:due_date_less_then_month],
          include_blank: '- Any -' 
        ) %>
    
        <label>1 month</label>
        <%= f.select(
          :due_date_one_month,
          @filterrific.select_options[:due_date_one_month],
          include_blank: '- Any -' 
        ) %>
    
        <label>3 months</label>
        <%= f.select(
          :due_date_three_month,
          @filterrific.select_options[:due_date_three_month],
          include_blank: '- Any -' 
        ) %>
    
        <label>3+ months</label>
        <%= f.select(
          :due_date_plus_three_month,
          @filterrific.select_options[:due_date_plus_three_month],
          include_blank: '- Any -' 
        ) %>
      </div>

      <div class="filter-col">
      <strong>Pages</strong>
        <label>Landing Page</label>
        <%= f.select(
          :pages_landing_pages,
          @filterrific.select_options[:pages_landing_pages],
          include_blank: '- Any -' 
        ) %>
      
        <label>2+ Pages</label>
        <%= f.select(
          :pages_two_pages,
          @filterrific.select_options[:pages_two_pages],
          include_blank: '- Any -' 
        ) %>
      </div>
    </div>
    <%= link_to 'Reset filters', reset_filterrific_url, class: "small" %>
    <%# add an automated spinner to your form when the list is refreshed %>
    <%= render_filterrific_spinner %>
  <% end %>

  <div class="project-list">
    <% if current_employer%>
      <h3><%= link_to '<i class="fas fa-plus-circle"></i> Create New Project'.html_safe, new_project_path %></h3>
    <%end%>
    <%= render(partial: 'projects/list', locals: { projects: @projects }) %>
  </div>
</div>

app/views/projects/index.js.erb
<% js = escape_javascript(
  render(partial: 'projects/list', locals: { projects: @projects })
) %>
$("#projects_list").html("<%= js %>");

app/views/projects/new.html.erb
<div class="top-buttons">
    <h3><%= link_to '<i class="fas fa-arrow-left"></i> Back'.html_safe, projects_path %></h3>
</div>
<h1>New Project</h1>
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %>
<% if current_employer && current_employer.id == @project.employer_id %>
  <h3><%= link_to '<i class="fas fa-edit"></i> Edit Project'.html_safe, edit_project_path(@project) %></h3> 
<%end%>
<div class="project-container">
 
  <div class="project-main">
    <strong>Project</strong>  <%= @project.project_name %>
    <br>

    <strong>Posted By</strong>  <%= link_to @project.employer.full_name, employer_path(@project.employer_id) %>
    <br>
    <strong>Description</strong>
    <br>
    <%= @project.project_description %>
    <br>
  
      <% if @project.developer_id%>
      <strong>Developer</strong> <a href="/developers/<%= @project.developer_id %>"><%= @project.developer.full_name %></a>
    <% end%>
    <br>
  
  <div class="project-appdev">
     <% if current_employer and @project.employer_id == current_employer.id %>
      <%# Employers: project owners choose the applicant  %>
      <%= render(partial: 'projects/form_employer_select_applicant', object: @project) %>
    <% elsif current_developer and @project.project_status == "open" and !@project.aplications.where(developer: current_developer).exists? %>
      <%# Developers: New application for devs that haven't applied %>
      <%= render(partial: 'projects/form_developer_apply', object: @project) %>         
    <% end %>
  </div>

   <% if current_employer and @project.employer_id == current_employer.id and @project.project_status == "in process" %>
      <p id='please_confirm'>Please confirm that the project is complete.</p> 
     <a data-remote="true" href='/confirm/<%= @project.id%>'>Confirm</a> 
    <% end %>

  <div class="project-review">
  <strong>Project Review</strong>
    <br>
    <%= link_to '<i class="fas fa-pen"></i> Write a Review'.html_safe, new_project_review_path(@project),class: "small" %>
    <br>
    <table style= "width: 100%">

      <% @reviews.each do |review| %>
        <tr>
          <td>
            <strong><%= review.title %></strong>
            <br>
            <%= review.review %>
          </td>
        </tr>
      <% end %>
      </table>
    </div>

  </div>

  <%# Sidebar %>
  <div class="project-side">
    <table>
    <strong>Status</strong><br>
    <li><span class="project-status" id="project-status"><%= @project.project_status %></span></li>
    <br>
    <strong>Due Date</strong>
      <% if @project.due_date_less_then_month %>
        <li>&lt; 1 month</li>
      <% end %>
      <% if @project.due_date_one_month %>
        <li>1 month</li>
      <% end %>
      <% if @project.due_date_three_month %>
        <li>&gt; 3 months</li>
      <% end %>
      <% if @project.due_date_plus_three_month %>
        <li>3+ months</li>
      <% end %>
    <br>
    <strong>Platform</strong>
      <% if @project.plattform_desktop %>
        <li>Desktop</li>
      <% end %>
      <% if @project.plattform_mobile %>
        <li>Mobile</li>
      <% end %>
      <% if @project.platform_tablet %>
        <li>Tablet</li>
      <% end %>
    <br>
    <strong>Assets</strong>
      <% if @project.assets_text %>
        <li>Text</li>
      <% end %>
      <% if @project.assets_images %>
        <li>Images</li>
      <% end %>
      <% if @project.assets_videos %>
        <li>Videos</li>
      <% end %>
      <% if @project.assets_audio %>
        <li>Audio</li>
      <% end %>
      <% if @project.assets_database %>
        <li>Database</li>
      <% end %>
    <br>
    <strong>Page(s)</strong>
      <% if @project.pages_landing_pages %>
        <li>Landing Page</li>
      <% end %>
      <% if @project.pages_two_pages %>
        <li>2+ Pages</li>
    <% end %>
    
  </table>
  </div>
</div>