config/routes.rb
Rails.application.routes.draw do
  
  resources :aplications
  # resources :reviews
  # project/id/new
 
  resources :projects do 
    resources :reviews, except: [:show, :index]
    resources :employers

    member do
      get 'apply'
    end

     
     
    
  end
  get '/confirm/:id', to: "projects#confirm_complete"
  root 'welcome#index'

  resources :messages, only: [:index, :create] do
    get '/chat/:user_id', action: :chat, as: 'chat', on: :collection
  end

  devise_for :employers, :controllers => { :registrations => 'employers/registrations' }
  devise_for :developers, path: 'developers', :controllers => { registrations: 'developers/registrations' }
 
  get '/developers', to: 'developers#index'
  get '/developers/:id', to: 'developers#show', as: 'developer'
  

  as :employers do
    get '/employers', to: 'employers#index'
    get '/employers/:id', to: 'employers#show', as: 'employer'
    get '/employers/my/projects', to: 'employers#index_projects'
  end

  as :developers do
    get '/developers/my/projects', to: 'developers#index_projects'
  end
  
  get '/dashboard', to: 'welcome#dashboard'
  get '/login', to: 'welcome#login'
end

app/models/employer.rb
class Employer < ApplicationRecord
  has_many :projects
  has_many :developers, through: :projects
  has_many :reviews
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 # instead of deleting, indicate the user requested a delete & timestamp it  
 
  def soft_delete
    update_attribute(:first_name, "account")
    update_attribute( :last_name , 'deleted')  
    update_attribute(:deleted_at, Time.current)  
  end  

  # ensure user account is active  
  def active_for_authentication?  
    super && !deleted_at  
  end  

  # provide a custom message for a deleted account   
  def inactive_message   
    !deleted_at ? super : :deleted_account  
  end

  def full_name
   "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/employers/confirmations_controller.rb
# frozen_string_literal: true

class Employers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employers/passwords_controller.rb
# frozen_string_literal: true

class Employers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employers/registrations_controller.rb
# frozen_string_literal: true

class Employers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do
      resource.image.attach(io: File.open(get_default_avatar_path), filename: 'avatar.jpg')
      resource.save
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :first_name,
      :last_name,
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :first_name,
      :last_name,
      :email,
      :description,
      :company_name,
      :phone_number,
      :state,
      :image
    ])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employers/sessions_controller.rb
# frozen_string_literal: true

class Employers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employers/unlocks_controller.rb
# frozen_string_literal: true

class Employers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
    @employer = Employer.find(params[:id])
    @open_projects = Project.where({ employer_id: @employer.id, project_status: "open" })
    @inprogress_projects = Project.where({ employer_id: @employer.id, project_status: "in process" })
    @complete_projects = Project.where({ employer_id: @employer.id, project_status: "complete" })
    

  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /employers/my/projects
  def index_projects
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:email, :first_name, :last_name, :description, :phone_number, :state, :company_name, :image)
      # params.fetch(:employer, {})
    end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_with(model: employer, local: true) do |form| %>
  <% if employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><%= f.text_area :first_name %>
    <%= f.label :last_name %><%= f.text_area :last_name %> <br/>
    <%= f.label :city %><%= f.text_area :city %>
    Bio <%= f.text_area :description %>
    <%= f.label :phone_number %><%= f.text_area :phone_number %>
    <%= f.label :email %><%= f.text_area :email %>
    <%= f.label :company_name %><%= f.text_area :company_name %>
    <%= f.label :image%><%= f.file_field :image%>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employers/edit.html.erb
<%= link_to 'Back', employers_path %>
<h1>Edit Client</h1>
<%= render 'form', employer: @employer %>

app/views/employers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="card-container">
  <% @employers.each do |employer| %>
    <div class="card-profile">
      
      <div class="image">
        <%if employer.image.attached? %>
          <%= image_tag (employer.image)%>
        <% end %>
      </div>

      <div class="content">
        <%= link_to employer.full_name, employer_path(employer), class: 'header' %>
        
        <div class="meta">
          <%= employer.created_at%>
        </div>

        <div class="description">
          <%= employer.company_name%>
        </div>

        <div class="extra content">
          
          <%= mail_to employer.email, '<i class="far fa-envelope"></i> Email'.html_safe + ' ' + employer.first_name %>
          <br/>
          <% if current_developer %>
            <%= link_to '<i class="far fa-comments"></i> Message'.html_safe + ' ' + employer.first_name, chat_messages_path(employer) %>
          <% end %>
          <br/>
          <%= link_to 'More Info', employer_path(employer) %>
        </div>
      </div>  
    </div>
    <% end %>   
</div>

app/views/employers/index_projects.erb
<h1>Open projects</h1>
<h1>Projects In Process</h1>
<h1>Complete Projects</h1>

app/views/employers/new.html.erb
<h1>New Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Back', employers_path %>

app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to '<i class="fas fa-edit"></i> Edit Profile'.html_safe, '/employers/edit'%>
<div class="show-profile">
<div class="ui card">
        <div class="image">
          <%if @employer.image.attached? %>
            <%= image_tag (@employer.image)%>
          <% end %>
        </div>

        <div class="content">
          <div class="header">
            <%=@employer.full_name%>
          </div>

          <div class="meta">
            <%= @employer.created_at%>
          </div>

          <div class="content">
            <% if !@employer.company_name.nil? %>
              <strong>Company Name</strong> <%= @employer.company_name%>
              <br />
            <% end %>
            <% if !@employer.company_url.nil? %>
              <strong>Company Site</strong> <%= @employer.company_url%>
              <br />
            <% end %>
            <strong>Contact</strong> <%= @employer.email%>
          </div>

          <div class="description">
            <% if !@employer.description.nil? %>
              <strong>Description</strong> <%= @employer.description%>
              <br />
            <% end %>
          </div>
  
          <div class="extra content">
            <% if !@employer.city.nil? %>
              <strong>City</strong> <%= @employer.city%>
              <br />
            <% end %>
            <% if !@employer.zip.nil? %>
              <strong>Zip</strong> <%= @employer.zip%>
              <br />
            <% end %>
          </div>
        </div>   
      </div>

  <div class="proj-profile">
    <h1>Projects</h1>
    <span><strong>Open</strong></span>
    <%@open_projects.each do |open_project| %>
      <li><a href='/projects/<%=open_project.id%>'><%= open_project.project_name%></a></li>
    <%end%>
    <br>
    <span><strong>In Process</strong></span>
    <%@inprogress_projects.each do |inprogress_project| %>
      <li><a href='/projects/<%=inprogress_project.id%>'><%= inprogress_project.project_name%></a></li>
    <%end%>
    <br>
    <% if !@complete_projects.each.nil? %>
      <span><strong>Complete</strong></span>
      <%@complete_projects.each do |complete_project| %>
        <li><a href='/projects/<%=complete_project.id%>'><%= complete_project.project_name%></a></li>
      <%end%>
    <% end %>

  </div>
</div>

 