config/routes.rb
Rails.application.routes.draw do
  
  resources :aplications
  # resources :reviews
  # project/id/new
 
  resources :projects do 
    resources :reviews, except: [:show, :index]
    resources :employers

    member do
      get 'apply'
    end

     
     
    
  end
  get '/confirm/:id', to: "projects#confirm_complete"
  root 'welcome#index'

  resources :messages, only: [:index, :create] do
    get '/chat/:user_id', action: :chat, as: 'chat', on: :collection
  end

  devise_for :employers, :controllers => { :registrations => 'employers/registrations' }
  devise_for :developers, path: 'developers', :controllers => { registrations: 'developers/registrations' }
 
  get '/developers', to: 'developers#index'
  get '/developers/:id', to: 'developers#show', as: 'developer'
  

  as :employers do
    get '/employers', to: 'employers#index'
    get '/employers/:id', to: 'employers#show', as: 'employer'
    get '/employers/my/projects', to: 'employers#index_projects'
  end

  as :developers do
    get '/developers/my/projects', to: 'developers#index_projects'
  end
  
  get '/dashboard', to: 'welcome#dashboard'
  get '/login', to: 'welcome#login'
end

app/views/layouts/application.html.erb
<head>
    <title>JumpStart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <header>
    <div class="top-nav">
      <div class="logo">
        <a href="/">
          <%= image_tag 'logo.png', class: 'logo' %>
        </a>
      </div>
      <div class="links">
        <% if developer_signed_in? %>
          <%= active_link_to 'MESSAGES', messages_path %>
          <%= active_link_to 'PROFILE', developer_path(current_developer.id) %>
          <%= active_link_to 'LOG OUT', destroy_developer_session_path, method: :delete %> 
        <% elsif employer_signed_in? %>
          <%= active_link_to 'MESSAGES', messages_path %>
          <%= active_link_to 'PROFILE', employer_path(current_employer.id) %>
          <%= link_to 'LOG OUT', destroy_employer_session_path, method: :delete %>
        <% else %> 
          <%= link_to 'LOGIN / SIGN UP', login_path %>
        <% end %>
      </div>
    </div>
    <div class="navigation-bar">
      <%= active_link_to 'PROJECTS', projects_path, class: "link" %>
      <%= active_link_to 'DEVELOPERS', developers_path, class: "link" %>
      <%= active_link_to 'EMPLOYERS', employers_path, class: "link" %> 
    </div>
    </header>
    <div class="main-container">
    <%= yield %>
    </div>

  <footer>
    © JUMPSTART
  </footer>
  </body>